### ISSUE TITLE
設定項目＞モニターを保存の問題

### ISSUE THREAD

**Issue by NSTMai** [ansonsiva/screenTimelapseZ#10]
1）設定において『モニターを保存>全てのモニター/メインのモニター/他のモニター』とありますが、これらは何が違いますか？
全て試してみましたが、3つともフルスクリーンを録画していて、違いがありませんでした。

2）有料版は、時間制限のほかにlite版と何が違うのか教えてください。

**Comment by ansonsiva** [comment]
1. この設定は、複数のディスプレイを使用するユーザー向けのものであり、1つのディスプレイを使用している場合は、この設定を変更してもあまり違いがありません。
2. 有料版は使用回数の制限を解除するだけであり、機能はLite版と同じです。

**Comment by ansonsiva** [comment]
> 1）設定において『モニターを保存>全てのモニター/メインのモニター/他のモニター』とありますが、これらは何が違いますか？
> 
> 全て試してみましたが、3つともフルスクリーンを録画していて、違いがありませんでした。
> 
> 
> 
> 2）有料版は、時間制限のほかにlite版と何が違うのか教えてください。
> 
> 


1. この設定は、複数のディスプレイを使用するユーザー向けのものであり、1つのディスプレイを使用している場合は、この設定を変更してもあまり違いがありません。
2. 有料版は使用回数の制限を解除するだけであり、機能はLite版と同じです。
