### ISSUE TITLE
Recording only my desktop...

### ISSUE THREAD

**Issue by AlmantasRozenas** [ansonsiva/screenTimelapseZ#3]
It is recording only my desktop view, not Sketchup... What can I do ? 

I find your program as very good.

**Comment by ansonsiva** [comment]
> It is recording only my desktop view, not Sketchup... What can I do ?
> 
> I find your program as very good.

With macOS Catalina (10.15), Apple introduced new security and privacy features for your Mac.

In order to capture screen shorts and screen recordings, you have to grant it access to the Screen Recording permission.
