### ISSUE TITLE
Save Mp4 is greyed out

### ISSUE THREAD

**Issue by FerminBHC** [ansonsiva/screenTimelapseZ#5]
I have about a 17min video from a 17 hr recording with your Screen TimelapseZ Lite for Mac, but I think I hit the 50 export limit, so the option to Save Mp4 is greyed out. I don’t want to loose that video, what can I do?

I recently bought the full version.

**Comment by ansonsiva** [comment]
HI,
    the temp pic files should save at the folder "/var/folders/x0/0b9t4y2x0958d9flsy549l9r0000gn/T/com.github.ansonsiva.timeLapseZ/display1"
If you can't find exact same folder. Maybe you can try search "com.github.ansonsiva.timeLapseZ" in finder.

I suggest that you should copy all the pic some folder else and combine them use quicktime player or imovie.
Don't end the timelapsez app ,it will clear the temp folder.

**Comment by FerminBHC** [comment]
Thanks
